#!/usr/bin/env python3

# Copyright 2026 Christopher Newport University
# Capable Humanitarian Robotics and Intelligent Systems Lab (CHRISLAB)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Inspect one or compare two Slugs YAML specification files.

With one YAML file, this tool checks each temporal-logic formula block for
invalid formulas and logically equivalent duplicates. With two YAML files, it
also compares proposition blocks and reports formulas that do not have an
equivalent formula in the other file.

The input files are the YAML specifications consumed or generated by the Slugs
spec loader, not raw `.structuredslugs` files. Use `count_slugs_specs` for raw
Slugs section counts.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
import re

import yaml


PROP_BLOCKS = ('env_props', 'sys_props', 'env_init', 'sys_init')
FORMULA_BLOCKS = ('env_trans', 'sys_trans', 'env_liveness', 'sys_liveness')
SYMPY_INSTALL_HINT = (
    'SymPy is required for formula inspection. Install it with '
    '`sudo apt install python3-sympy` or `python3 -m pip install sympy`.'
)
_SYMPY_SYMBOLS = None
_SYMPY_BOOLALG = None


@dataclass
class FormulaToken:
    """Token produced by the Slugs formula tokenizer."""

    kind: str
    value: str


@dataclass
class FormulaBlockAnalysis:
    """Parsed representation and consistency results for one formula block."""

    formulas: list[str]
    normalized: list[str]
    expressions: list[object]
    invalid: list[tuple[int, str]]
    duplicates: list[tuple[int, int, str]]

    @property
    def ok(self):
        """Return true when the block has no invalid or duplicate formulas."""
        return not self.invalid and not self.duplicates


def normalize_next_notation(expr):
    """Normalize Slugs next-state shorthand into explicit `next(name)` terms."""
    normalized = str(expr)

    def replace_next_neg(match):
        inner = match.group(1).strip()
        if inner.startswith('!'):
            return f'!next({inner[1:].strip()})'
        return f'next({inner})'

    normalized = re.sub(r'next\(\s*([^)]+)\)', replace_next_neg, normalized)

    def replace_prime(match):
        return f'next({match.group(1)})'

    return re.sub(r"\b([a-zA-Z_][a-zA-Z0-9_]*)'", replace_prime, normalized)


def term_symbol_name(term):
    """Convert a Slugs proposition term into a SymPy-safe symbol name."""
    return term.replace('next(', 'next_').replace(')', '')


def load_sympy():
    """Import optional SymPy helpers used by formula inspection."""
    global _SYMPY_SYMBOLS
    global _SYMPY_BOOLALG

    if _SYMPY_SYMBOLS is not None and _SYMPY_BOOLALG is not None:
        return _SYMPY_SYMBOLS, _SYMPY_BOOLALG

    try:
        from sympy import false, symbols, true
        from sympy.logic.boolalg import (
            And,
            Equivalent,
            Implies,
            Not,
            Or,
            Xor,
            simplify_logic,
        )
    except ImportError as exc:
        raise RuntimeError(SYMPY_INSTALL_HINT) from exc

    _SYMPY_SYMBOLS = symbols
    _SYMPY_BOOLALG = {
        'And': And,
        'Equivalent': Equivalent,
        'Implies': Implies,
        'Not': Not,
        'Or': Or,
        'Xor': Xor,
        'false': false,
        'simplify_logic': simplify_logic,
        'true': true,
    }
    return _SYMPY_SYMBOLS, _SYMPY_BOOLALG


def tokenize_formula(expr):
    """Tokenize the supported Slugs propositional formula subset."""
    tokens = []
    position = 0
    token_pattern = re.compile(
        r'\s*(<-->|<->|->|[()!&|]|'
        r'next\([a-zA-Z_][a-zA-Z0-9_]*\)|'
        r'[a-zA-Z_][a-zA-Z0-9_]*)'
    )

    while position < len(expr):
        match = token_pattern.match(expr, position)
        if not match:
            raise ValueError(f"unexpected token near '{expr[position:]}'")

        value = match.group(1)
        position = match.end()

        if value in ('<->', '<-->'):
            tokens.append(FormulaToken('EQUIV', value))
        elif value == '->':
            tokens.append(FormulaToken('IMPLIES', value))
        elif value == '&':
            tokens.append(FormulaToken('AND', value))
        elif value == '|':
            tokens.append(FormulaToken('OR', value))
        elif value == '!':
            tokens.append(FormulaToken('NOT', value))
        elif value == '(':
            tokens.append(FormulaToken('LPAREN', value))
        elif value == ')':
            tokens.append(FormulaToken('RPAREN', value))
        elif value in ('True', 'False'):
            tokens.append(FormulaToken('BOOL', value))
        else:
            tokens.append(FormulaToken('TERM', value))

    tokens.append(FormulaToken('END', ''))
    return tokens


class FormulaParser:
    """Recursive-descent parser for Slugs propositional formulas."""

    def __init__(self, tokens, sympy_api):
        """Create a parser over tokens using the provided SymPy constructors."""
        self.tokens = tokens
        self.index = 0
        self.sympy_symbols = sympy_api[0]
        self.boolalg = sympy_api[1]

    def current(self):
        """Return the current token."""
        return self.tokens[self.index]

    def accept(self, kind):
        """Consume the current token when it has the expected kind."""
        if self.current().kind != kind:
            return None
        token = self.current()
        self.index += 1
        return token

    def expect(self, kind):
        """Consume an expected token or raise a parser error."""
        token = self.accept(kind)
        if token is None:
            raise ValueError(f"expected {kind}, got '{self.current().value}'")
        return token

    def parse(self):
        """Parse one complete formula."""
        expr = self.parse_equivalence()
        if self.current().kind != 'END':
            raise ValueError(f"unexpected token '{self.current().value}'")
        return expr

    def parse_equivalence(self):
        """Parse `<->` and `<-->` expressions."""
        expr = self.parse_implication()
        while self.accept('EQUIV'):
            expr = self.boolalg['Equivalent'](expr, self.parse_implication())
        return expr

    def parse_implication(self):
        """Parse right-associative implication expressions."""
        expr = self.parse_or()
        if self.accept('IMPLIES'):
            expr = self.boolalg['Implies'](expr, self.parse_implication())
        return expr

    def parse_or(self):
        """Parse disjunction expressions."""
        terms = [self.parse_and()]
        while self.accept('OR'):
            terms.append(self.parse_and())
        if len(terms) == 1:
            return terms[0]
        return self.boolalg['Or'](*terms)

    def parse_and(self):
        """Parse conjunction expressions."""
        terms = [self.parse_not()]
        while self.accept('AND'):
            terms.append(self.parse_not())
        if len(terms) == 1:
            return terms[0]
        return self.boolalg['And'](*terms)

    def parse_not(self):
        """Parse negation expressions."""
        if self.accept('NOT'):
            return self.boolalg['Not'](self.parse_not())
        return self.parse_primary()

    def parse_primary(self):
        """Parse a parenthesized expression, boolean literal, or proposition."""
        if self.accept('LPAREN'):
            expr = self.parse_equivalence()
            self.expect('RPAREN')
            return expr

        token = self.accept('BOOL')
        if token is not None:
            if token.value == 'True':
                return self.boolalg['true']
            return self.boolalg['false']

        token = self.accept('TERM')
        if token is not None:
            return self.sympy_symbols(term_symbol_name(token.value))

        raise ValueError(f"expected formula term, got '{self.current().value}'")


def parse_formula(expr):
    """Parse one Slugs formula into a SymPy boolean expression."""
    sympy_api = load_sympy()
    normalized = normalize_next_notation(expr)
    return normalized, FormulaParser(tokenize_formula(normalized), sympy_api).parse()


def formulas_to_sympy(formulas):
    """Convert formula strings into SymPy expressions where possible."""
    load_sympy()
    normalized = []
    expressions = []
    invalid = []

    for index, formula in enumerate(formulas):
        try:
            normalized_formula, expression = parse_formula(formula)
            normalized.append(normalized_formula)
            expressions.append(expression)
        except (TypeError, ValueError) as exc:
            normalized.append(normalize_next_notation(formula))
            expressions.append(None)
            invalid.append((index, str(exc)))

    return normalized, expressions, invalid


def expressions_equivalent(expr1, expr2):
    """Return true when SymPy can prove two parsed formulas are equivalent."""
    if expr1 is None or expr2 is None:
        return False

    _symbols, boolalg = load_sympy()
    try:
        simplified = boolalg['simplify_logic'](boolalg['Xor'](expr1, expr2))
        return simplified == boolalg['false']
    except (NotImplementedError, TypeError, ValueError):
        return False


def analyze_formula_block(formulas):
    """Analyze one list of formulas for parse errors and duplicates."""
    normalized, expressions, invalid = formulas_to_sympy(formulas)
    duplicates = []
    previous = []

    for index, expr in enumerate(expressions):
        if expr is None:
            continue

        duplicate_of = None
        for previous_index, previous_expr in previous:
            if expressions_equivalent(expr, previous_expr):
                duplicate_of = previous_index
                break

        if duplicate_of is None:
            previous.append((index, expr))
        else:
            duplicates.append((index, duplicate_of, normalized[index]))

    return FormulaBlockAnalysis(
        formulas=list(formulas),
        normalized=normalized,
        expressions=expressions,
        invalid=invalid,
        duplicates=duplicates,
    )


def normalize_spec_keys(spec):
    """Return a copy with lower-case keys and INPUT/OUTPUT aliases normalized."""
    if not isinstance(spec, dict):
        return {}
    if 'specs' in spec:
        spec = spec['specs']

    normalized = {}
    for key, value in spec.items():
        lower_key = key.lower()
        if lower_key == 'input':
            lower_key = 'env_props'
        elif lower_key == 'output':
            lower_key = 'sys_props'
        normalized[lower_key] = value or []
    return normalized


def load_spec(path_text):
    """Load and normalize a Slugs YAML spec file."""
    path = Path(path_text).expanduser()
    with path.open(encoding='utf-8') as spec_file:
        return path, normalize_spec_keys(yaml.safe_load(spec_file))


def print_block_analysis(block, analysis, label='spec'):
    """Print one formula block analysis summary."""
    print(f"------------ Inspecting '{block}' in {label} ------------")
    print(f'    Total specs: {len(analysis.expressions)}')
    print(f'    Invalid specs: {len(analysis.invalid)}')
    print(f'    Duplicate/equivalent specs detected: {len(analysis.duplicates)}')

    for index, error in analysis.invalid:
        print(f'    Invalid at index {index}: {analysis.formulas[index]}')
        print(f'      {error}')

    for index, duplicate_of, formula in analysis.duplicates:
        print(f'    Duplicate at index {index} matches index {duplicate_of}: {formula}')


def inspect_spec(spec, label='spec', blocks=FORMULA_BLOCKS):
    """Inspect one spec for internal formula consistency."""
    ok = True
    for block in blocks:
        formulas = spec.get(block, [])
        if not formulas:
            print(f"------------ No '{block}' in {label} ------------")
            continue
        analysis = analyze_formula_block(formulas)
        print_block_analysis(block, analysis, label)
        ok = ok and analysis.ok
    return ok


def normalized_values(spec, block):
    """Return normalized string values for a proposition block."""
    return [str(value).strip().replace(' ', '') for value in spec.get(block, [])]


def compare_prop_block(block, spec1, spec2):
    """Compare set-equivalence of one proposition block."""
    props1 = normalized_values(spec1, block)
    props2 = normalized_values(spec2, block)
    missing_from_2 = [prop for prop in props1 if prop not in props2]
    missing_from_1 = [prop for prop in props2 if prop not in props1]

    if not props1 and not props2:
        print(f"  No '{block}' in either file.")
        return True

    if missing_from_1 or missing_from_2:
        print(f"  '{block}' are NOT the same.")
        for prop in missing_from_2:
            print(f"    '{prop}' is in 1 but not 2")
        for prop in missing_from_1:
            print(f"    '{prop}' is in 2 but not 1")
        return False

    print(f"  '{block}' are the same.")
    return True


def unmatched_formula_indexes(source, target):
    """Return indexes in source that have no equivalent expression in target."""
    unmatched = []
    target_exprs = [expr for expr in target.expressions if expr is not None]
    for index, expr in enumerate(source.expressions):
        if expr is None:
            continue
        if not any(expressions_equivalent(expr, target_expr) for target_expr in target_exprs):
            unmatched.append(index)
    return unmatched


def compare_formula_block(block, spec1, spec2):
    """Compare logical equivalence of one formula block between two specs."""
    print(f"------------ Comparing '{block}' ------------")
    analysis1 = analyze_formula_block(spec1.get(block, []))
    analysis2 = analyze_formula_block(spec2.get(block, []))
    print_block_analysis(block, analysis1, '1')
    print_block_analysis(block, analysis2, '2')

    unmatched1 = unmatched_formula_indexes(analysis1, analysis2)
    unmatched2 = unmatched_formula_indexes(analysis2, analysis1)

    for index in unmatched1:
        print(f'  {index:3d} in 1 has no equivalent in 2: [{analysis1.formulas[index]}]')
    for index in unmatched2:
        print(f'  {index:3d} in 2 has no equivalent in 1: [{analysis2.formulas[index]}]')

    print(
        f'   Spec 1 has {len(unmatched1)} unmatched specs out of '
        f'{len(analysis1.formulas)} total specs.'
    )
    print(
        f'   Spec 2 has {len(unmatched2)} unmatched specs out of '
        f'{len(analysis2.formulas)} total specs.'
    )
    return analysis1.ok and analysis2.ok and not unmatched1 and not unmatched2


def compare_spec_pair(spec1, spec2):
    """Compare proposition and formula blocks between two Slugs YAML specs."""
    ok = True
    for block in PROP_BLOCKS:
        print(30 * '-')
        ok = compare_prop_block(block, spec1, spec2) and ok

    for block in FORMULA_BLOCKS:
        print(30 * '-')
        ok = compare_formula_block(block, spec1, spec2) and ok

    return ok


def build_argument_parser():
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description=(
            'Inspect one Slugs YAML spec for internal consistency, or compare '
            'two Slugs YAML specs for matching propositions and formulas.'
        ),
        epilog=(
            'Formula parsing and equivalence checks require optional SymPy. '
            'Install it with `sudo apt install python3-sympy` or '
            '`python3 -m pip install sympy`.'
        ),
    )
    parser.add_argument(
        'spec',
        nargs='+',
        help='One or two YAML spec files to inspect.',
    )
    parser.add_argument(
        '--strict',
        action='store_true',
        help='Exit with status 1 when invalid, duplicate, or unmatched formulas are found.',
    )
    return parser


def main(argv=None):
    """Run the Slugs spec inspection command-line tool."""
    parser = build_argument_parser()
    args = parser.parse_args(argv)

    if len(args.spec) > 2:
        parser.error('provide one spec to inspect or two specs to compare')

    try:
        load_sympy()
        path1, spec1 = load_spec(args.spec[0])
        if len(args.spec) == 1:
            print(f"Inspecting '{path1}'")
            ok = inspect_spec(spec1, str(path1))
        else:
            path2, spec2 = load_spec(args.spec[1])
            print(f"Comparing '{path1}'")
            print(f"     with '{path2}'")
            ok = compare_spec_pair(spec1, spec2)
    except OSError as exc:
        parser.exit(1, f'error: {exc}\n')
    except RuntimeError as exc:
        parser.exit(1, f'error: {exc}\n')
    except yaml.YAMLError as exc:
        parser.exit(1, f'error: failed to read YAML: {exc}\n')

    if args.strict and not ok:
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
