# Copyright 2026 Christopher Newport University
# Capable Humanitarian Robotics and Intelligent Systems Lab (CHRISLAB)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Explicit-state semantic checks for Slugs strategy automata."""

from collections import deque
from dataclasses import dataclass, field
import os
import re
import time

from flexbe_synthesis_core.graph_utils import tarjan_scc
from flexbe_synthesis_slugs.helpers.slugs_automaton import SlugsAutomaton


PARSE_ERROR = 'PARSE_ERROR'
DEADLOCK = 'DEADLOCK'
PROTOCOL_VIOLATION = 'PROTOCOL_VIOLATION'
UNDECLARED_OUTCOME = 'UNDECLARED_OUTCOME'
INVALID_TRANSITION = 'INVALID_TRANSITION'
GOAL_UNREACHABLE = 'GOAL_UNREACHABLE'
GOAL_UNREACHABLE_TRAP = 'GOAL_UNREACHABLE_TRAP'
BOUNDED_FAILURE_VIOLATION = 'BOUNDED_FAILURE_VIOLATION'
SPEC_EVAL_ERROR = 'SPEC_EVAL_ERROR'

# Warnings that report protocol enforcement was disabled rather than a strategy
# defect. These are diagnostic/terminal-only for the pipeline wrapper (see
# processes/strategy_auditor.py's TERMINAL_ONLY_WARNINGS), which imports these
# constants instead of matching on independently-duplicated literal text, so
# editing the wording here can't silently desync the routing.
PROTOCOL_DISABLED_REDUCED_WARNING = (
    'Protocol enforcement disabled: reduced automata store merged '
    'state input labels, not concrete per-edge outcome observations.'
)
PROTOCOL_DISABLED_SHAPE_WARNING = (
    'Protocol enforcement disabled: automaton/spec shape does '
    'not expose strict one-step activation/outcome semantics.'
)

_SECTION_RE = re.compile(r'^\[[A-Z_]+\]$')
_IDENT_RE = re.compile(r'\b[A-Za-z_][A-Za-z0-9_]*\b')
_INDEXED_VAR_RE = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):\d+\.\.\.\d+$')
_ACTION_COMMENT_RE = re.compile(r'^#\s*(\d+)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)')


@dataclass(frozen=True)
class CapabilitySpec:
    """Semantic variable names and outcome classes for one capability."""

    name: str
    activate: str
    outcomes: dict
    success_outcomes: frozenset = field(default_factory=frozenset)
    failure_outcomes: frozenset = field(default_factory=frozenset)
    max_consecutive_failures: int | None = None


@dataclass
class AuditorConfig:
    """Derived semantic settings used by the explicit-state auditor."""

    capabilities: dict
    goal_outcomes: list
    transition_outcomes: list
    activation_variable: str | None = None
    activation_map: dict = field(default_factory=dict)
    encoding: str = 'explicit_variables'
    enforce_protocol: bool = True
    warnings: list = field(default_factory=list)


class AuditTimeout(RuntimeError):
    """Raised internally when the audit exceeds its configured time budget."""


def empty_result(valid=True, message='Strategy audit passed.'):
    """Return the public result object with stable keys."""
    return {
        'valid': valid,
        'incomplete': False,
        'failure_kinds': [],
        'failure_kind': None,
        'message': message,
        'counterexample_trace': [],
        'bad_scc_states': [],
        'warnings': [],
    }


def failure_result(kind, message, trace=None, warnings=None, bad_scc_states=None):
    """Return a failed public result object."""
    result = empty_result(valid=False, message=message)
    result['failure_kinds'] = [kind]
    result['failure_kind'] = kind
    result['counterexample_trace'] = trace or []
    result['bad_scc_states'] = bad_scc_states or []
    result['warnings'] = warnings or []
    return result


def parse_compiled_slugs_sections(spec_path):
    """Scan a compiled `.slugsin` file into section-name to lines mapping."""
    sections = {}
    current = None
    with open(spec_path, encoding='utf-8') as spec_file:
        for line in spec_file:
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue
            if _SECTION_RE.fullmatch(stripped):
                current = stripped.strip('[]')
                sections.setdefault(current, [])
                continue
            if current is not None:
                sections[current].append(stripped)
    return sections


def default_spec_path(specs_output_dir_path, spec_name):
    """Return the compiled Slugs input path generated by the existing pipeline."""
    return os.path.join(
        specs_output_dir_path,
        'synthesis_byproducts',
        f'{spec_name}.slugsin',
    )


def derive_config(
    system_capabilities,
    state_mappings,
    slugs_specification,
    goal_outcomes,
):
    """Derive auditor semantics from existing pipeline payloads."""
    warnings = []
    capabilities = {}
    transition_outcomes = list(
        system_capabilities.get(
            'transition_outcomes',
            state_mappings.get('transition_outcomes', ['completed', 'failure']),
        )
    )
    if not transition_outcomes:
        transition_outcomes = ['completed', 'failure']
        warnings.append('No transition outcomes found; using completed/failure defaults.')

    for cap_name, cap_data in system_capabilities.get('capabilities', {}).items():
        state_data = cap_data.get('state') or cap_data.get('behavior') or {}
        declared = _declared_outcomes(cap_name, state_data, transition_outcomes)
        success = {
            key
            for key in declared
            if key in ('completed', 'complete', 'success') or key.startswith('comp')
        }
        failure = {
            key
            for key in declared
            if key in ('failure', 'failed', 'fail') or key.startswith('fail')
        }
        max_failures = cap_data.get('max_consecutive_failures')
        if max_failures is None:
            max_failures = cap_data.get('bounded_failure_limit')
        if max_failures is not None:
            max_failures = int(max_failures)

        capabilities[cap_name] = CapabilitySpec(
            name=cap_name,
            activate=f'{cap_name}_a',
            outcomes=declared,
            success_outcomes=frozenset(success),
            failure_outcomes=frozenset(failure),
            max_consecutive_failures=max_failures,
        )

    if not capabilities:
        warnings.append('No capabilities found; protocol checks will be limited.')

    mapped_goals = _derive_goal_outcomes(
        system_capabilities,
        state_mappings,
        slugs_specification,
        goal_outcomes,
    )
    activation_variable, activation_map = _derive_parsed_activation_map(
        slugs_specification,
        capabilities,
    )
    encoding = 'parsed_capability' if activation_map else 'explicit_variables'
    return AuditorConfig(
        capabilities=capabilities,
        goal_outcomes=mapped_goals,
        transition_outcomes=transition_outcomes,
        activation_variable=activation_variable,
        activation_map=activation_map,
        encoding=encoding,
        warnings=warnings,
    )


def _declared_outcomes(cap_name, state_data, transition_outcomes):
    """Return outcome-name to variable-name mapping for one capability."""
    outcomes = {}
    raw_outcomes = state_data.get('outcomes', {})
    for outcome_data in raw_outcomes.values():
        if not isinstance(outcome_data, dict):
            continue
        remapping = str(outcome_data.get('remapping', '')).strip()
        if not remapping:
            continue
        outcomes[remapping] = f'{cap_name}_{remapping[0]}'

    if not outcomes:
        for outcome in transition_outcomes:
            if outcome:
                outcomes[outcome] = f'{cap_name}_{outcome[0]}'
    return outcomes


def _derive_goal_outcomes(system_capabilities, state_mappings, slugs_specification,
                          goal_outcomes):
    """Return top-level state-machine outcomes used as semantic goals."""
    if goal_outcomes:
        return list(goal_outcomes)
    mappings = system_capabilities.get('sm_outcome_mappings')
    if not mappings:
        mappings = state_mappings.get('sm_outcome_mappings', {})
    goals = set(mappings.values())
    sys_props = set(slugs_specification.get('sys_props', []))
    for formula in slugs_specification.get('sys_liveness', []):
        for goal in _formula_goal_props(formula, sys_props):
            goals.add(goal)
    return sorted(goals)


def _formula_goal_props(formula, sys_props):
    """Return simple non-capability goal props named by a liveness formula."""
    if not isinstance(formula, str):
        return []
    expression = formula.split('#', 1)[0].strip()
    if not expression:
        return []
    goals = []
    for token in _IDENT_RE.findall(expression):
        if token not in sys_props:
            continue
        if token.endswith('_a') or token.endswith('_m'):
            continue
        if token not in goals:
            goals.append(token)
    return goals


def _derive_parsed_activation_map(slugs_specification, capabilities):
    """Return parsed numeric activation variable and index-to-capability map."""
    sys_props = list(slugs_specification.get('sys_props', []))
    indexed_variables = []
    for prop in sys_props:
        if not isinstance(prop, str):
            continue
        match = _INDEXED_VAR_RE.match(prop.strip())
        if match:
            indexed_variables.append(match.group(1))
    activation_variable = None
    if 'capability' in indexed_variables:
        activation_variable = 'capability'
    elif len(indexed_variables) == 1:
        activation_variable = indexed_variables[0]
    if not activation_variable:
        return None, {}

    activation_map = {}
    capability_names = set(capabilities)
    for prop in sys_props:
        if not isinstance(prop, str):
            continue
        match = _ACTION_COMMENT_RE.match(prop.strip())
        if not match:
            continue
        index = int(match.group(1))
        cap_name = match.group(2)
        if index == 0 or cap_name not in capability_names:
            continue
        activation_map[index] = cap_name
    return activation_variable, activation_map


class StrategyAuditor:
    """Validate an explicit Slugs automaton against semantic progress checks."""

    def __init__(self, timeout_s=5.0):
        self.timeout_s = float(timeout_s)
        self.deadline = None

    def audit(
        self,
        automaton_data,
        spec_path,
        system_capabilities,
        state_mappings,
        slugs_specification,
        goal_outcomes=None,
    ):
        """Run all enabled checks and return a public result dictionary."""
        self.deadline = time.monotonic() + self.timeout_s if self.timeout_s > 0 else None
        warnings = []
        try:
            sections = parse_compiled_slugs_sections(spec_path)
            warnings.extend(self._spec_warnings(sections))
            config = derive_config(
                system_capabilities,
                state_mappings,
                slugs_specification,
                goal_outcomes or [],
            )
            warnings.extend(config.warnings)
            try:
                automaton = SlugsAutomaton.from_dict(automaton_data)
            except ValueError as exc:
                if 'transition to missing target' in str(exc):
                    return failure_result(INVALID_TRANSITION, str(exc),
                                          warnings=warnings)
                raise
            if automaton.size() == 0:
                return failure_result(
                    PARSE_ERROR,
                    'Strategy automaton is empty.',
                    warnings=warnings,
                )

            initial = self._initial_states(automaton)
            if not initial:
                return failure_result(
                    PARSE_ERROR,
                    'Strategy automaton has no initial state.',
                    warnings=warnings,
                )
            if (
                isinstance(automaton_data, dict)
                and automaton_data.get('reduced_automaton')
            ):
                config.enforce_protocol = False
                warnings.append(PROTOCOL_DISABLED_REDUCED_WARNING)
            else:
                config.enforce_protocol = self._should_enforce_protocol(
                    automaton,
                    slugs_specification,
                    config,
                )
            if not config.enforce_protocol:
                warnings.append(PROTOCOL_DISABLED_SHAPE_WARNING)

            result = self._build_product_graph(automaton, initial, config, warnings)
            if not result['valid']:
                return result

            result = self._check_goal_reachability(result, config, warnings)
            if not result['valid']:
                return result

            result = self._check_goal_unreachable_traps(result, config, warnings)
            if not result['valid']:
                return result

            passed = empty_result()
            passed['warnings'] = warnings
            return passed
        except AuditTimeout:
            result = empty_result(valid=True, message='Strategy audit timed out; presumed OK.')
            result['incomplete'] = True
            result['warnings'] = warnings + [
                f'StrategyAuditor timed out after {self.timeout_s:g}s; '
                'audit incomplete and presumed valid.'
            ]
            return result
        except (OSError, TypeError, ValueError, KeyError) as exc:
            return failure_result(PARSE_ERROR, f'Strategy audit parse error: {exc}')

    def _spec_warnings(self, sections):
        """Return non-fatal warnings from the compiled spec scan."""
        warnings = []
        if 'INPUT' not in sections:
            warnings.append('Compiled Slugs spec has no [INPUT] section.')
        if 'OUTPUT' not in sections:
            warnings.append('Compiled Slugs spec has no [OUTPUT] section.')
        return warnings

    def _build_product_graph(self, automaton, initial_states, config, warnings):
        """Explore strategy x pending-capability x bounded-failure counters."""
        nodes = set()
        adjacency = {}
        parent = {}
        goals = set()
        queue = deque()
        zero_counters = tuple((name, 0) for name in sorted(config.capabilities))
        for state_name in initial_states:
            state = automaton[state_name]
            pending_name = None
            if state:
                activated = self._activated_capabilities(state, config)
                if len(activated) > 1:
                    return failure_result(
                        PROTOCOL_VIOLATION,
                        f"State '{state.name}' activates multiple capabilities: "
                        f'{activated}.',
                        warnings=warnings,
                    )
                pending_name = activated[0] if activated else None
            product = (state_name, pending_name, zero_counters)
            queue.append(product)
            parent[product] = None

        while queue:
            self._check_timeout()
            product = queue.popleft()
            if product in nodes:
                continue
            nodes.add(product)
            state_name, pending_name, counters = product
            state = automaton[state_name]
            if state is None:
                return failure_result(
                    PARSE_ERROR,
                    f"Product state references missing strategy state '{state_name}'.",
                )
            if self._is_goal_state(state, config):
                goals.add(product)
            if not state.transitions:
                return failure_result(
                    DEADLOCK,
                    f"Strategy state '{state.name}' has no outgoing transitions.",
                    trace=self._trace(parent, product, automaton, config),
                )

            next_nodes = []
            for target_name in state.transitions:
                target = automaton[target_name]
                if target is None:
                    return failure_result(
                        INVALID_TRANSITION,
                        f"State '{state.name}' transitions to missing state '{target_name}'.",
                        trace=self._trace(parent, product, automaton, config),
                        warnings=warnings,
                    )
                observed = self._observed_outcomes(target, pending_name, config)
                next_counters = counters
                if config.enforce_protocol:
                    violation = self._protocol_violation(
                        pending_name,
                        target,
                        observed,
                        config,
                    )
                    if violation:
                        kind, message = violation
                        trace = self._trace(parent, product, automaton, config)
                        trace.append(
                            self._trace_entry(target, pending_name, observed, config)
                        )
                        return failure_result(kind, message, trace=trace,
                                              warnings=warnings)

                activated = self._activated_capabilities(target, config)
                if config.enforce_protocol and len(activated) > 1:
                    trace = self._trace(parent, product, automaton, config)
                    trace.append(self._trace_entry(target, pending_name, observed, config))
                    return failure_result(
                        PROTOCOL_VIOLATION,
                        f"State '{target.name}' activates multiple capabilities: "
                        f'{activated}.',
                        trace=trace,
                        warnings=warnings,
                    )
                next_pending = activated[0] if activated else None

                if config.enforce_protocol:
                    next_counters = self._advance_counters(counters, pending_name,
                                                           observed, config, next_pending)
                    counter_violation = self._counter_violation(next_counters, config)
                    if counter_violation:
                        return failure_result(
                            BOUNDED_FAILURE_VIOLATION,
                            counter_violation,
                            trace=self._trace(parent, product, automaton, config),
                            warnings=warnings,
                        )

                next_product = (target.name, next_pending, next_counters)
                if self._is_goal_state(target, config) or self._is_goal_observation(
                    pending_name,
                    observed,
                    config,
                ):
                    goals.add(next_product)
                next_nodes.append(next_product)
                if next_product not in parent:
                    parent[next_product] = product
                    queue.append(next_product)

            adjacency[product] = next_nodes

        return {
            'valid': True,
            'nodes': nodes,
            'adjacency': adjacency,
            'parent': parent,
            'goals': goals,
            'automaton': automaton,
        }

    def _check_goal_reachability(self, graph, config, warnings):
        """Fail if configured goal outcomes are never reachable."""
        if not config.goal_outcomes:
            return graph
        if graph['goals']:
            return graph
        return failure_result(
            GOAL_UNREACHABLE,
            f'None of the goal outcomes are reachable: {config.goal_outcomes}.',
            warnings=warnings,
        )

    def _check_goal_unreachable_traps(self, graph, config, warnings):
        """Fail on reachable cyclic SCCs that exclude configured goal outcomes."""
        if not config.goal_outcomes:
            return graph
        components = tarjan_scc(graph['nodes'], graph['adjacency'])
        comp_lookup = {}
        for index, component in enumerate(components):
            for node in component:
                comp_lookup[node] = index

        def _is_cyclic(component):
            return len(component) > 1 or any(
                node in graph['adjacency'].get(node, [])
                for node in component
            )

        cyclic_comps = {
            index for index, component in enumerate(components) if _is_cyclic(component)
        }

        reverse_comp_graph = {index: set() for index in range(len(components))}
        for source, targets in graph['adjacency'].items():
            source_comp = comp_lookup[source]
            for target in targets:
                target_comp = comp_lookup[target]
                if source_comp != target_comp:
                    reverse_comp_graph[target_comp].add(source_comp)

        # Seed backward reachability only from goal components the goal actually
        # recurs in (i.e. cyclic ones). A non-cyclic goal-containing component is
        # visited at most once before execution leaves it for good, which does not
        # certify recurrence for goals with no system-side persistence guarantee
        # (e.g. an environment-reported completion input used as a goal outcome
        # for strategies with no terminal SM output). This is a no-op for
        # terminal-output goals: their `<outcome> -> <outcome>'` sys_trans trap
        # always makes the containing component cyclic already.
        goal_comps = {comp_lookup[node] for node in graph['goals']} & cyclic_comps
        can_reach_goal = set(goal_comps)
        stack = list(goal_comps)
        while stack:
            self._check_timeout()
            comp_index = stack.pop()
            for predecessor in reverse_comp_graph.get(comp_index, set()):
                if predecessor in can_reach_goal:
                    continue
                can_reach_goal.add(predecessor)
                stack.append(predecessor)

        for comp_index in sorted(cyclic_comps):
            self._check_timeout()
            if comp_index in can_reach_goal:
                continue
            bad_states = sorted({node[0] for node in components[comp_index]})
            return failure_result(
                GOAL_UNREACHABLE_TRAP,
                'Reachable cyclic SCC excludes all configured goal outcomes.',
                warnings=warnings,
                bad_scc_states=bad_states,
            )
        return graph

    def _should_enforce_protocol(self, automaton, slugs_specification, config):
        """Return True when automaton shape supports strict one-step protocol checks."""
        explicit_activation_outputs = [
            var
            for var in automaton.output_variables
            if isinstance(var, str) and var.endswith('_a')
        ]
        if not explicit_activation_outputs and not config.activation_map:
            return False
        env_trans = slugs_specification.get('env_trans', [])
        if not self._has_immediate_outcome_protocol(
            env_trans,
            config,
            explicit_activation_outputs,
        ):
            return False

        for state in automaton.automaton:
            if state.is_initial and state.incoming:
                return False
        return True

    def _has_immediate_outcome_protocol(self, env_trans, config, activation_outputs):
        """Return True if the spec encodes activation -> next outcome rules."""
        formulas = [
            formula.split('#', 1)[0].replace(' ', '')
            for formula in env_trans
            if isinstance(formula, str)
        ]
        if not formulas:
            return False
        activation_outputs = set(activation_outputs)
        for cap in config.capabilities.values():
            activation_terms = self._activation_terms(cap, config, activation_outputs)
            if not activation_terms:
                continue
            supported = False
            for formula in formulas:
                if not any(f'{term}->' in formula for term in activation_terms):
                    continue
                for outcome_name in self._outcome_terms(cap, config):
                    direct = f"{outcome_name}'"
                    next_direct = f'next({outcome_name})'
                    if direct in formula or next_direct in formula:
                        supported = True
                        break
                if supported:
                    break
            if not supported:
                return False
        return True

    def _activation_terms(self, cap, config, activation_outputs):
        """Return normalized activation terms for explicit or parsed encodings."""
        if config.activation_map:
            for index, cap_name in config.activation_map.items():
                if cap_name == cap.name:
                    return [
                        f'{config.activation_variable}={index}',
                        f'({config.activation_variable}={index})',
                    ]
            return []
        if cap.activate in activation_outputs:
            return [cap.activate]
        return []

    def _outcome_terms(self, cap, config):
        """Return outcome proposition names that may satisfy a capability attempt."""
        terms = []
        for outcome_name, var_name in cap.outcomes.items():
            terms.extend([outcome_name, var_name])
        if config.activation_map:
            terms.extend(config.transition_outcomes)
        return list(dict.fromkeys(terms))

    def _initial_states(self, automaton):
        """Return effective initial state names using existing automaton conventions."""
        explicit = [state.name for state in automaton.automaton if state.is_initial]
        if explicit:
            return explicit
        roots = [state.name for state in automaton.automaton if not state.incoming]
        if roots:
            return roots[:1]
        return [automaton.automaton[0].name] if automaton.automaton else []

    def _activated_capabilities(self, state, config):
        """Return capability names activated in a strategy state."""
        if config.activation_map and config.activation_variable:
            value = state.output_values.get(config.activation_variable)
            if value is None:
                return []
            try:
                index = int(value)
            except (TypeError, ValueError):
                return []
            cap_name = config.activation_map.get(index)
            return [cap_name] if cap_name else []

        return [
            cap.name
            for cap in config.capabilities.values()
            if cap.activate in state.output_variables or state.output_values.get(cap.activate)
        ]

    def _observed_outcomes(self, state, pending_name, config):
        """Return outcome names observed on entry to `state`."""
        observed = []
        inputs = set(state.input_variables)
        input_values = {
            name
            for name, value in state.input_values.items()
            if value is True or value == 1
        }
        active_inputs = inputs | input_values
        if not pending_name:
            for outcome in config.transition_outcomes:
                if outcome in active_inputs:
                    observed.append(f'protocol:{outcome}')

        if pending_name:
            cap = config.capabilities[pending_name]
            for outcome, var_name in cap.outcomes.items():
                if var_name in active_inputs or outcome in active_inputs:
                    observed.append(outcome)
            for outcome in config.transition_outcomes:
                if outcome in active_inputs and outcome not in cap.outcomes:
                    observed.append(f'undeclared:{outcome}')

        for cap in config.capabilities.values():
            for outcome, var_name in cap.outcomes.items():
                if var_name in active_inputs and cap.name != pending_name:
                    observed.append(f'{cap.name}:{outcome}')
        return observed

    def _protocol_violation(self, pending_name, state, observed, config):
        """Return `(kind, message)` for protocol violations, otherwise None."""
        protocol_outcomes = [out for out in observed if out.startswith('protocol:')]
        if protocol_outcomes:
            if config.activation_map and pending_name is None:
                # Parsed/enumerated specs force the action variable non-zero
                # on every transition after the first, so `pending_name` is
                # None only when leaving the true initial (null-action)
                # state. The generic outcome props aren't constrained there,
                # so Slugs may legally branch on an env-asserted outcome
                # before any real capability has ever run. That branch is
                # behaviorally inert (it carries no information the system
                # can act on), not a protocol violation.
                return None
            return (
                PROTOCOL_VIOLATION,
                f"State '{state.name}' observes generic outcome(s) with no "
                f'pending capability: {protocol_outcomes}.',
            )
        unexpected = [out for out in observed if ':' in out]
        if unexpected:
            return (
                PROTOCOL_VIOLATION,
                f"State '{state.name}' observes outcome(s) with no pending "
                f'capability: {unexpected}.',
            )
        if pending_name and not observed:
            return (
                PROTOCOL_VIOLATION,
                f"Capability '{pending_name}' has no declared outcome at "
                f"successor state '{state.name}'.",
            )
        if pending_name and len(observed) > 1:
            return (
                PROTOCOL_VIOLATION,
                f"Capability '{pending_name}' has multiple outcomes at "
                f"state '{state.name}': {observed}.",
            )
        return None

    def _advance_counters(self, counters, pending_name, observed, config, next_pending):
        """Update consecutive failure counters after an observed attempt outcome.

        A capability's counter tracks failures only within its current unbroken
        streak of immediately-repeated activation. It resets to 0 whenever that
        streak breaks for any reason: success, or the strategy moving on to a
        different (or no) pending capability instead of retrying. Without this,
        two failures separated by an unrelated capability's entire activation
        would count as if they were consecutive.
        """
        counter_dict = dict(counters)
        if pending_name and observed:
            cap = config.capabilities[pending_name]
            outcome = observed[0]
            if outcome in cap.success_outcomes:
                counter_dict[pending_name] = 0
            elif outcome in cap.failure_outcomes:
                if cap.max_consecutive_failures is None:
                    # No configured bound means _counter_violation() never inspects this
                    # capability's count (see its `continue` below), so tracking exact
                    # counts here only inflates product-state identity for no reason.
                    # An unbounded retry loop would otherwise mint a new distinct
                    # product state on every failed attempt, making the product-graph
                    # BFS in _build_product_graph() run forever instead of terminating.
                    counter_dict[pending_name] = 0
                else:
                    counter_dict[pending_name] = counter_dict.get(pending_name, 0) + 1
        # Only the capability immediately becoming pending next can be mid-streak;
        # everyone else's streak just broke (including `pending_name` itself, if
        # it failed but isn't being retried), so their counters reset to 0.
        for name in counter_dict:
            if name != next_pending:
                counter_dict[name] = 0
        return tuple((name, counter_dict.get(name, 0)) for name in sorted(counter_dict))

    def _counter_violation(self, counters, config):
        """Return a bounded-failure message when a counter exceeds its limit."""
        counter_dict = dict(counters)
        for cap in config.capabilities.values():
            if cap.max_consecutive_failures is None:
                continue
            count = counter_dict.get(cap.name, 0)
            if count > cap.max_consecutive_failures:
                return (
                    f"Capability '{cap.name}' failed {count} consecutive attempt(s); "
                    f'limit is {cap.max_consecutive_failures}.'
                )
        return None

    def _is_goal_state(self, state, config):
        """Return True when state output or input asserts a configured goal outcome.

        Goal outcomes are usually system-asserted SM outcomes (e.g. `finished`), but
        some examples (e.g. coffee, which has no sm_outcome_mappings and is designed
        to cycle forever) have no system-output goal to anchor on; their only
        observable "progress" signal is an environment-reported completion input
        (e.g. `br_c`). Checking both sides lets goal_outcomes reference either.
        """
        for outcome in config.goal_outcomes:
            if outcome in state.output_variables or state.output_values.get(outcome):
                return True
            if outcome in state.input_variables or state.input_values.get(outcome):
                return True
        return False

    def _is_goal_observation(self, pending_name, observed, config):
        """Return True when a generic observed outcome satisfies a concrete goal.

        Parsed/enumerated encodings intentionally replace per-capability input labels
        such as `br_c` with generic outcome labels such as `completed`.  While brew is
        pending, observing `completed` is therefore the semantic event represented by
        `br_c`, even though the literal input label is absent from the automaton.
        """
        if not pending_name or not observed:
            return False
        cap = config.capabilities.get(pending_name)
        if cap is None:
            return False
        goals = set(config.goal_outcomes)
        for outcome in observed:
            if ':' in outcome:
                continue
            if outcome in goals or cap.outcomes.get(outcome) in goals:
                return True
        return False

    def _trace(self, parent, product, automaton, config):
        """Return counterexample product path from the initial product to `product`."""
        path = []
        cursor = product
        while cursor is not None:
            state = automaton[cursor[0]]
            path.append(self._trace_entry(state, cursor[1], [], config, cursor[2]))
            cursor = parent.get(cursor)
        path.reverse()
        return path

    def _trace_entry(self, state, pending_name, observed, config, counters=None):
        """Return one diagnostic trace entry."""
        if counters is None:
            counters = tuple((name, 0) for name in sorted(config.capabilities))
        return {
            'state': state.name,
            'input_values': dict(state.input_values),
            'input_variables': list(state.input_variables),
            'output_values': dict(state.output_values),
            'output_variables': list(state.output_variables),
            'pending_capability': pending_name,
            'outcome_observed': list(observed),
            'failure_counters': dict(counters),
        }

    def _check_timeout(self):
        """Raise when the configured wall-clock audit budget is exhausted."""
        if self.deadline is not None and time.monotonic() > self.deadline:
            raise AuditTimeout()
